version: '3.8'

services:
  postgres:
    container_name: postgres_avito
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - 5432:5432

  app:
    build: .
    container_name: segment-service
    hostname: segment-service
    image: segment-service
    environment:
      - PG_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_DB:-postgres}:5432/${POSTGRES_DB:-postgres}
      - PORT=${HTTP_PORT:-8080}
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  pg-data: